/* listorder version 1.0.1
* Copyright (c) 2012 Michel Bobillier aka Athos99 www.athos99.com
*
* GNU General Public License, version 3 (GPL-3.0) http://www.gnu.org/licenses/gpl-3.0.en.html
*
* Description:
*   listorder is a jQuery Plugin for ordered and filtered select option list. Can ordered and filter other list of type li or div
*   http://www.athos99.com/listorder
*
*   Usage : $("#idlist").listorder();
*           $("select").listorder( {filter:'asc'});
*           $("ul").listorder( {filter:'asc',child:'ul'});
*/
(function(d){function i(b){switch(b.settings.order){case "asc":b.savelist.sort(function(a,c){a=b.settings.childValue.call(a);c=b.settings.childValue.call(c);return d.isNumeric(a)&&d.isNumeric(c)?a-c:a<c?-1:a>c?1:0});break;case "desc":b.savelist.sort(function(a,c){c=b.settings.childValue.call(c);a=b.settings.childValue.call(a);return d.isNumeric(c)&&d.isNumeric(a)?c-a:c<a?-1:c>a?1:0});break;case "rand":b.savelist.sort(function(){return 0.5>Math.random()?1:-1})}}function g(b,a){var c=a.settings.filter.toLowerCase();
d.each(a.savelist,function(d,f){var g=!0;c.length&&(g=a.settings.filterExact?0===a.settings.childValue.call(f).toLowerCase().indexOf(c):-1!==a.settings.childValue.call(f).toLowerCase().indexOf(c));g?b.append(f):f.detach()})}function k(b){var a=b.data("listorder"),c=a.settings.filter;a.settings.filter="";g(b,a);a.settings.filter=c;b.children(a.settings.child).each(function(){d(this).attr("selected","selected")})}function j(b,a,c){b.off("click.listorder");b.removeAttr("selected");a.listorder("remove",
b);c.listorder("add",b);b.on("click.listorder",function(b){j(d(this),c,a,b)})}var h={init:function(b){return this.each(function(){var a={},c=d(this);a.settings=d.extend({order:"asc",child:"option",childValue:function(){return this.text()},filter:"",filterExact:!1,submitAll:!1},b);d.isNumeric(a.settings.filterExact)&&(a.settings.filterExact=parseInt(a.settings.filterExact,10));d.isNumeric(a.settings.submitAll)&&(a.settings.submitAll=parseInt(a.settings.submitAll,10));var e=[];c.children(a.settings.element).each(function(){e.push(d(this))});
a.savelist=e;c.data("listorder",a);i(a);g(c,a);if(a.settings.submitAll)c.closest("form").on("submit",function(){k(c)})})},filter:function(b,a){return this.each(function(){var c=d(this),e=c.data("listorder");void 0!==a&&(d.isNumeric(a)&&(a=parseInt(a,10)),e.settings.filterExact=a);e.settings.filter="string"===typeof b?b:"";g(c,e)})},selectAll:function(){return this.each(function(){k(d(this))})},unselectAll:function(){return this.each(function(){var b=d(this),a=b.data("listorder");d.each(a.savelist,
function(){d(this).removeAttr("selected")});g(b,a)})},display:function(){return this.each(function(){var b=d(this),a=b.data("listorder");g(b,a)})},exclude:function(b){return this.each(function(){var a=d(this),c=a.data("listorder"),e=[];if(void 0!==b){b.children(c.settings.child).each(function(){e[d(this).text()]=1});var f;for(f=0;f<c.savelist.length;)c.savelist[f].text()in e?(c.savelist.splice(f,1),d(a.children()[f]).detach()):f++}g(a,c)})},include:function(b){return this.each(function(){var a=d(this),
c=a.data("listorder"),e=[];void 0!=b&&(d.each(c.savelist,function(){e[d(this).text()]=d(this)}),b.children(c.settings.child).each(function(){d(this).text()in e||c.savelist.push(d(this).clone())}),i(c));g(a,c)})},order:function(b){return this.each(function(){var a=d(this),c=a.data("listorder");c.settings.order=b;i(c);g(a,c)})},add:function(b,a){return this.each(function(){var c=!0,e=d(this),f=e.data("listorder");a||d.each(f.savelist,function(){b.text()===d(this).text()&&(c=!1)});c&&f.savelist.push(b);
i(f);g(e,f)})},remove:function(b){return this.each(function(){var a="text",c=d(this),e=c.data("listorder");"string"!=typeof b&&(a="object");for(var f=0;f<e.savelist.length;)("object"==a?e.savelist[f][0]===b[0]:e.settings.childValue.call(e.savelist[f])===b)?(e.savelist[f].detach(),e.savelist.splice(f,1)):f++;g(c,e)})},duo:function(b){var a=d(this),c=a.data("listorder"),e=b.data("listorder");a.children(c.settings.child).on("click.listorder",function(){d(this).removeAttr("selected");a.listorder("remove",
d(this))});b.children(e.settings.child).on("click.listorder",function(){d(this).removeAttr("selected");var b=d(this).clone().on("click",function(){a.listorder("remove",d(this))});a.listorder("add",b)})},duoInclude:function(b){var a=d(this);h.include.call(b,a);h.duo.call(a,b)},duoExclude:function(b){var a=d(this),c=a.data("listorder"),e=a.data("listorder");h.exclude.call(b,a);a.children(c.settings.child).on("click.listorder",function(c){j(d(this),a,b,c)});b.children(e.settings.child).on("click.listorder",
function(c){j(d(this),b,a,c)})},setChildValue:function(b){return this.each(function(){var a=d(this),c=a.data("listorder");c.settings.childValue=b;i(c);g(a,c)})}};d.fn.listorder=function(b){if(h[b])return h[b].apply(this,Array.prototype.slice.call(arguments,1));if("object"===typeof b||!b)return h.init.apply(this,arguments);d.error("Method "+b+" does not exist on jQuery.listorder");return!1}})(jQuery);